/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Depreciated;

import Model.Folder;
import Model.Rep;
import Model.User;
import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author NoahS
 */
public class RepManagerWin extends javax.swing.JFrame {
    private DefaultListModel<String> dlm;
    private DefaultTreeModel dtm;
    private DefaultMutableTreeNode root;
    private User user;
    private Rep selectedRep;
    /**
     * Creates new form RepManagerWin
     */
    public RepManagerWin(User user) {
        this.user = user;
        
        dlm = new DefaultListModel();
        
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("root");
        dtm = new DefaultTreeModel(root);
        
        int i = 0;
        for(Rep r : user.getReps()){
            dlm.add(i, r.getName());
            i++;
        }
        
        initComponents();
    }
    public void update(){
        int i = lstRep.getSelectedIndex();
        Folder f = user.getTimelineRep().getContents().getSubfolder(dlm.elementAt(i));
        root = f.getTree();
        dtm = new DefaultTreeModel(root);
        treeMedia.setModel(dtm);
        /*
        // This handles repository contents
        int i = lstRep.getSelectedIndex();
        selectedRep = user.getRepAt(i);
        root = selectedRep.getRoot();
        dtm = new DefaultTreeModel(root);
        treeMedia.setModel(dtm);
        */
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstRep = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        treeMedia = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstRep.setModel(dlm);
        lstRep.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRepValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstRep);

        jLabel1.setText("Your Public Repositories");

        treeMedia.setModel(dtm);
        treeMedia.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeMediaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(treeMedia);

        jLabel2.setText("Repository Media");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2))
                .addContainerGap(731, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstRepValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRepValueChanged
        update();
    }//GEN-LAST:event_lstRepValueChanged

    private void treeMediaValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeMediaValueChanged
        
        /*
        // This handles reposiory contents
        if(treeMedia.getSelectionPath() != null && selectedRep != null){
            TreePath path = treeMedia.getSelectionPath();
            FileRequest fr = selectedRep.getContents().follow(path, selectedRep.getName());
            System.out.println(fr.toString());
        }
        */
    }//GEN-LAST:event_treeMediaValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstRep;
    private javax.swing.JTree treeMedia;
    // End of variables declaration//GEN-END:variables
}
