package View;

import Model.Rep;
import Model.User;
import com.mycompany.vp2final.TimelineChangeHandler;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.tree.TreePath;

public class RepInfoPanel extends javax.swing.JPanel implements TimelineChangeHandler{

    private User user;
    public RepInfoPanel() {
        initComponents();
    }
    
    public void setUser(User user){
        this.user = user;
    }
    
    @Override
    public void onChange(Rep r){
        updateComponents(r);
    }
    public void resetComponents(){
        jtfRepName.setText("Repository");
        jtfRepLink.setText("Link");
        jtfRepOwnerName.setText("Owner");
        jtfRepCreateDate.setText("Date Created");
        jtfLastCommitDate.setText("Date Last Updated");
        lblRepPic.setIcon(null);
        languagePanel.reset();
    }
    public void updateComponents(Rep r){
        jtfRepName.setText(r.getName());
        jtfRepLink.setText(r.getHtml_url());
        jtfRepOwnerName.setText(r.getOwner().getLogin());
        jtfRepCreateDate.setText(r.getDateCreated().toString());
        jtfLastCommitDate.setText(r.getDateLastPushed().toString());
        languagePanel.changeLangs(r.getLangs());
        try{
            if(user.ownsMediaRep()){
                String logoUrl = user.getTimelineRep().getContents().follow(new TreePath(new String[]{r.getName(), "logo.png"})).getDownload_url();
                BufferedImage img = ImageIO.read(new URL(logoUrl));
                ImageIcon icon = new ImageIcon(img.getScaledInstance(lblRepPic.getWidth(), lblRepPic.getHeight(), Image.SCALE_SMOOTH));
                lblRepPic.setIcon(icon);
            }
        }
        catch(MalformedURLException e){
            e.printStackTrace();
        }
        catch(IOException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRepPic = new javax.swing.JLabel();
        jtfRepName = new javax.swing.JTextField();
        jtfRepLink = new javax.swing.JTextField();
        jtfRepCreateDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfWatchersValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtfCommitValue = new javax.swing.JTextField();
        jtfRepOwnerName = new javax.swing.JTextField();
        jtfLastCommitDate = new javax.swing.JTextField();
        languagePanel = new View.JGraphics.LanguagePanel();

        lblRepPic.setBackground(new java.awt.Color(255, 255, 255));
        lblRepPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRepPic.setOpaque(true);

        jtfRepName.setText("Repository Name");
        jtfRepName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRepNameActionPerformed(evt);
            }
        });

        jtfRepLink.setText("Repository Link");

        jtfRepCreateDate.setText("Date");
        jtfRepCreateDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfRepCreateDateActionPerformed(evt);
            }
        });

        jLabel3.setText("Watchers: ");

        jtfWatchersValue.setText("100");
        jtfWatchersValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfWatchersValueActionPerformed(evt);
            }
        });

        jLabel1.setText("Commits: ");

        jtfCommitValue.setText("10");
        jtfCommitValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCommitValueActionPerformed(evt);
            }
        });

        jtfRepOwnerName.setText("Owner");

        jtfLastCommitDate.setText("Date");

        javax.swing.GroupLayout languagePanelLayout = new javax.swing.GroupLayout(languagePanel);
        languagePanel.setLayout(languagePanelLayout);
        languagePanelLayout.setHorizontalGroup(
            languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 438, Short.MAX_VALUE)
        );
        languagePanelLayout.setVerticalGroup(
            languagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 212, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblRepPic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtfRepLink, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jtfRepName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfRepOwnerName))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jtfRepCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jtfLastCommitDate)))
                    .addComponent(languagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfWatchersValue, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCommitValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRepPic, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRepName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfRepOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfRepLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfRepCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLastCommitDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfWatchersValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jtfCommitValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(languagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfRepNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRepNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRepNameActionPerformed

    private void jtfRepCreateDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfRepCreateDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfRepCreateDateActionPerformed

    private void jtfWatchersValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfWatchersValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfWatchersValueActionPerformed

    private void jtfCommitValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCommitValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCommitValueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtfCommitValue;
    private javax.swing.JTextField jtfLastCommitDate;
    private javax.swing.JTextField jtfRepCreateDate;
    private javax.swing.JTextField jtfRepLink;
    private javax.swing.JTextField jtfRepName;
    private javax.swing.JTextField jtfRepOwnerName;
    private javax.swing.JTextField jtfWatchersValue;
    private View.JGraphics.LanguagePanel languagePanel;
    private javax.swing.JLabel lblRepPic;
    // End of variables declaration//GEN-END:variables
}
