/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Model.Folder;
import Model.Rep;
import Model.User;
import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author NoahS
 */
public class RepMediaManagerPanel extends javax.swing.JPanel {

    /**
     * Creates new form RepMediaManagerPanel
     */
    private DefaultListModel<String> dlm;
    private DefaultTreeModel dtm;
    private DefaultMutableTreeNode root;
    private User user;
    
    public RepMediaManagerPanel() {
        dlm = new DefaultListModel<>();
        root = new DefaultMutableTreeNode("");
        dtm = new DefaultTreeModel(root);
        initComponents();
    }
    
    public void setUser(User user){
        clear();
        this.user =  user;
        dlm.clear();
        int i = 0;
        for(Rep r : user.getReps()){
            dlm.add(i, r.getName());
            i++;
        }
        //lstRep.setModel(dlm);
    }
    public void clear(){
        dlm.clear();
        root = new DefaultMutableTreeNode("");
        dtm = new DefaultTreeModel(root);
        treeMedia.setModel(dtm);
    }
    
     public void update(){
        int i = lstRep.getSelectedIndex();
        if(i > -1 && i < dlm.getSize()){
            Folder f = user.getTimelineRep().getContents().getSubfolder(dlm.elementAt(i));
            root = f.getTree();
            dtm = new DefaultTreeModel(root);
            treeMedia.setModel(dtm);
        }
        
        /*
        // This handles repository contents
        int i = lstRep.getSelectedIndex();
        selectedRep = user.getRepAt(i);
        root = selectedRep.getRoot();
        dtm = new DefaultTreeModel(root);
        treeMedia.setModel(dtm);
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstRep = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        treeMedia = new javax.swing.JTree();

        lstRep.setModel(dlm);
        lstRep.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstRepValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstRep);

        treeMedia.setModel(dtm);
        treeMedia.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeMediaValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(treeMedia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(590, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lstRepValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstRepValueChanged
        update();
    }//GEN-LAST:event_lstRepValueChanged

    private void treeMediaValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeMediaValueChanged

        /*
        // This handles reposiory contents
        if(treeMedia.getSelectionPath() != null && selectedRep != null){
            TreePath path = treeMedia.getSelectionPath();
            FileRequest fr = selectedRep.getContents().follow(path, selectedRep.getName());
            System.out.println(fr.toString());
        }
        */
    }//GEN-LAST:event_treeMediaValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstRep;
    private javax.swing.JTree treeMedia;
    // End of variables declaration//GEN-END:variables
}
