/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.vp2final;

import Model.User;
import java.awt.CardLayout;

/**
 *
 * @author NoahS
 */
public class MainWin extends javax.swing.JFrame{

    /**
     * Creates new form MultiWindow
     */
    private User user;
    
    public MainWin() {
        initComponents();
        searchUserPanel.setVisible(false);
    }
    
    public void setUser(User user){
        this.user = user;
        winTimeline.setUser(user);
        
        if(user.ownsMediaRep()){
            repMediaManagerPanel.setUser(user);
        }
        else{
            repMediaManagerPanel.clear();
        }
        changePanel("timelineWindow");
    }
    public void changePanel(String cardName){
        CardLayout cardLayout = (CardLayout)pnlMain.getLayout();
        cardLayout.show(pnlMain, cardName);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        pnlMain = new javax.swing.JPanel();
        signInPanel = new View.SignInPanel();
        repMediaManagerPanel = new View.RepMediaManagerPanel();
        winTimeline = new View.TimelineWindowPanel();
        searchUserPanel = new View.SearchUserPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemSocialSearch = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemViewTimeline = new javax.swing.JMenuItem();
        itemViewRepMedia = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pnlMain.setLayout(new java.awt.CardLayout());
        pnlMain.add(signInPanel, "signInPanel");
        pnlMain.add(repMediaManagerPanel, "repMediaManagerPanel");
        pnlMain.add(winTimeline, "timelineWindow");

        jMenu1.setText("Social");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        itemSocialSearch.setText("Search");
        itemSocialSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSocialSearchActionPerformed(evt);
            }
        });
        jMenu1.add(itemSocialSearch);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("View");

        itemViewTimeline.setText("Timeline");
        itemViewTimeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewTimelineActionPerformed(evt);
            }
        });
        jMenu2.add(itemViewTimeline);

        itemViewRepMedia.setText("Rep Media");
        itemViewRepMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewRepMediaActionPerformed(evt);
            }
        });
        jMenu2.add(itemViewRepMedia);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Settings");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(693, 693, 693))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(searchUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filler1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemViewTimelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewTimelineActionPerformed
        changePanel("timelineWindow");
    }//GEN-LAST:event_itemViewTimelineActionPerformed

    private void itemViewRepMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewRepMediaActionPerformed
        changePanel("repMediaManagerPanel");
    }//GEN-LAST:event_itemViewRepMediaActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void itemSocialSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSocialSearchActionPerformed
        
        searchUserPanel.setVisible(true);
    }//GEN-LAST:event_itemSocialSearchActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        searchUserPanel.setVisible(false);
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JMenuItem itemSocialSearch;
    private javax.swing.JMenuItem itemViewRepMedia;
    private javax.swing.JMenuItem itemViewTimeline;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel pnlMain;
    private View.RepMediaManagerPanel repMediaManagerPanel;
    private View.SearchUserPanel searchUserPanel;
    private View.SignInPanel signInPanel;
    private View.TimelineWindowPanel winTimeline;
    // End of variables declaration//GEN-END:variables
}
