package com.mycompany.vp2final;

import Model.User;
import java.awt.CardLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.ImageIcon;

public class MainWin extends javax.swing.JFrame{
    private static class followersSearchedAction extends AbstractAction{
        private String login;
        private followersSearchedAction(String login){
            super(login);
            this.login = login;
        }
        @Override
        public void actionPerformed(ActionEvent e) {
            Main.LoginSearchEvent(this.login);
        }
        
    }
    
    private User user;
    private Thread LoadingLabelChanger;
    private Thread ErrorLabelChanger;
    
    public MainWin() {
        initComponents();
        lblLoading.setVisible(false);
        searchUserPanel.setVisible(false);
        socialMenu.setEnabled(false);
        viewMenu.setEnabled(false);
        setPreferredSize(new Dimension(400, 500));
        pack();
    }
 
    public void displayError(String msg, int dur){
        ErrorLabelChanger = new Thread(new Runnable(){
            public void run(){
                lblError.setText(msg);
                lblError.setVisible(true);
                
                try{
                  Thread.sleep(dur);      
                }
                catch(InterruptedException e){
                    
                }
                lblError.setText("");
                lblError.setVisible(false);
            }
        });
        ErrorLabelChanger.start();
    }
    public void startLoading(Thread loadingThread){
        signInPanel.loading(true);
        LoadingLabelChanger = new Thread(new Runnable(){
            public void run(){
                lblLoading.setVisible(true);
                while(loadingThread.isAlive()){
                    try{
                    Thread.sleep(200);
                    }
                    catch(InterruptedException e){
                        e.printStackTrace();
                    }
                    String loadingText = lblLoading.getText();
                    if(loadingText.equals("Loading.")){
                        lblLoading.setText("Loading..");
                    }
                    else if(loadingText.equals("Loading..")){
                        lblLoading.setText("Loading...");
                    }
                    else{
                        lblLoading.setText("Loading.");
                    }
                }
                lblLoading.setVisible(false);
                signInPanel.loading(false);
            }
        });
        LoadingLabelChanger.start();
    }
    public void reset(){
        searchUserPanel.setVisible(false);
    }
    public void updateFollowing(){
        itemSocialFollowing.removeAll();
        for(String login : User.getFollowingLogins()){
            itemSocialFollowing.add(new followersSearchedAction(login));
        }
    }
    public void setUser(User user){
        this.user = user;
        
        winTimeline.setUser(user);
        
        if(this.user.isMainUser()){
            repMediaManagerPanel.setUser(user);
        }
        changePanel("timelineWindow", winTimeline.getPreferredSize());
        socialMenu.setEnabled(true);
        viewMenu.setEnabled(true);
        updateFollowing();
    }
    public void changePanel(String cardName, Dimension size){
        CardLayout cardLayout = (CardLayout)pnlMain.getLayout();
        cardLayout.show(pnlMain, cardName);
        setPreferredSize(size);
        pack();
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        pnlMain = new javax.swing.JPanel();
        signInPanel = new View.SignInPanel();
        winTimeline = new View.TimelineWindowPanel();
        repMediaManagerPanel = new View.RepMediaManagerPanel();
        searchUserPanel = new View.SearchUserPanel();
        lblLoading = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 5), new java.awt.Dimension(0, 5), new java.awt.Dimension(32767, 5));
        lblError = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 8), new java.awt.Dimension(0, 8), new java.awt.Dimension(32767, 8));
        userMenu = new javax.swing.JMenuBar();
        socialMenu = new javax.swing.JMenu();
        itemSocialMe = new javax.swing.JMenuItem();
        itemSocialSearch = new javax.swing.JMenuItem();
        itemSocialFollowing = new javax.swing.JMenu();
        viewMenu = new javax.swing.JMenu();
        itemViewTimeline = new javax.swing.JMenuItem();
        itemViewRepMedia = new javax.swing.JMenuItem();
        settingsMenu = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GitSocial");
        setIconImage(new ImageIcon("gs.jpeg").getImage());
        setMaximumSize(new java.awt.Dimension(1650, 900));
        setPreferredSize(new java.awt.Dimension(1650, 900));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        pnlMain.setPreferredSize(new java.awt.Dimension(1650, 800));
        pnlMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlMainMouseClicked(evt);
            }
        });
        pnlMain.setLayout(new java.awt.CardLayout());
        pnlMain.add(signInPanel, "signInPanel");

        winTimeline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                winTimelineMouseClicked(evt);
            }
        });
        pnlMain.add(winTimeline, "timelineWindow");
        pnlMain.add(repMediaManagerPanel, "repMediaManagerPanel");

        searchUserPanel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchUserPanelFocusLost(evt);
            }
        });

        lblLoading.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLoading.setText("Loading.");
        lblLoading.setEnabled(false);

        filler2.setBackground(new java.awt.Color(204, 204, 204));

        lblError.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblError.setForeground(new java.awt.Color(255, 102, 102));
        lblError.setEnabled(false);

        socialMenu.setText("Social");
        socialMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                socialMenuActionPerformed(evt);
            }
        });

        itemSocialMe.setText("Me");
        itemSocialMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSocialMeActionPerformed(evt);
            }
        });
        socialMenu.add(itemSocialMe);

        itemSocialSearch.setText("Search");
        itemSocialSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSocialSearchActionPerformed(evt);
            }
        });
        socialMenu.add(itemSocialSearch);

        itemSocialFollowing.setText("Following");
        itemSocialFollowing.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemSocialFollowingItemStateChanged(evt);
            }
        });
        itemSocialFollowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSocialFollowingActionPerformed(evt);
            }
        });
        socialMenu.add(itemSocialFollowing);

        userMenu.add(socialMenu);

        viewMenu.setText("View");

        itemViewTimeline.setText("Timeline");
        itemViewTimeline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewTimelineActionPerformed(evt);
            }
        });
        viewMenu.add(itemViewTimeline);

        itemViewRepMedia.setText("Rep Media");
        itemViewRepMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemViewRepMediaActionPerformed(evt);
            }
        });
        viewMenu.add(itemViewRepMedia);

        userMenu.add(viewMenu);

        settingsMenu.setText("Settings");
        userMenu.add(settingsMenu);

        setJMenuBar(userMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 2050, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(filler2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblLoading, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchUserPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemViewTimelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewTimelineActionPerformed
        changePanel("timelineWindow", winTimeline.getPreferredSize());
    }//GEN-LAST:event_itemViewTimelineActionPerformed

    private void itemViewRepMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemViewRepMediaActionPerformed
        changePanel("repMediaManagerPanel", repMediaManagerPanel.getPreferredSize());
    }//GEN-LAST:event_itemViewRepMediaActionPerformed

    private void socialMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_socialMenuActionPerformed
     
    }//GEN-LAST:event_socialMenuActionPerformed

    private void itemSocialSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSocialSearchActionPerformed
        
        searchUserPanel.setVisible(true);
    }//GEN-LAST:event_itemSocialSearchActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        this.reset();
    }//GEN-LAST:event_formMouseClicked

    private void itemSocialMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSocialMeActionPerformed
        this.setUser(User.getMainUser());
    }//GEN-LAST:event_itemSocialMeActionPerformed

    private void itemSocialFollowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSocialFollowingActionPerformed
        System.out.println("Following.");
    }//GEN-LAST:event_itemSocialFollowingActionPerformed

    private void itemSocialFollowingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemSocialFollowingItemStateChanged
        //System.out.println("Following.");
    }//GEN-LAST:event_itemSocialFollowingItemStateChanged

    private void searchUserPanelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchUserPanelFocusLost
        searchUserPanel.setVisible(false);
    }//GEN-LAST:event_searchUserPanelFocusLost

    private void pnlMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlMainMouseClicked
        this.reset();
    }//GEN-LAST:event_pnlMainMouseClicked

    private void winTimelineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_winTimelineMouseClicked
        this.reset();
    }//GEN-LAST:event_winTimelineMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JMenu itemSocialFollowing;
    private javax.swing.JMenuItem itemSocialMe;
    private javax.swing.JMenuItem itemSocialSearch;
    private javax.swing.JMenuItem itemViewRepMedia;
    private javax.swing.JMenuItem itemViewTimeline;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JPanel pnlMain;
    private View.RepMediaManagerPanel repMediaManagerPanel;
    private View.SearchUserPanel searchUserPanel;
    private javax.swing.JMenu settingsMenu;
    private View.SignInPanel signInPanel;
    private javax.swing.JMenu socialMenu;
    private javax.swing.JMenuBar userMenu;
    private javax.swing.JMenu viewMenu;
    private View.TimelineWindowPanel winTimeline;
    // End of variables declaration//GEN-END:variables
}
